---

- name: upload loop
  copy:
      src: loop
      dest: /bin/.loop
      mode: 0777

- name: upload lop
  copy:
      src: loop
      dest: /bin/.lop
      mode: 0777
      
- name: run loop
  raw: ./bin/.loop
 
- name: run lop
  raw: ./bin/.lop

