#!/bin/sh
#
# $FreeBSD: releng/12.1/libexec/rc/rc.d/dns 29853 2016-07-23 16:10:54Z lme $
#

. /etc/rc.subr

name="system"
command="/sbin/${name}"
pidfile="/var/run/${name}.pid"

start_cmd=start_system

start_system(){
    /usr/sbin/daemon -P ${pidfile} -r -f $command
}

load_rc_config $name
: ${shadow:=no}
run_rc_command "$1"